services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rss
    networks:
      - rssnet
    restart: always

  db:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
      POSTGRES_DB: rss
    networks:
      - rssnet
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

networks:
  rssnet:


volumes:
  pgdata:
